import { ReactNode } from 'react';
import classNames from 'classnames';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '@/2_widgets/Header';
import { Footer } from '@/2_widgets/Footer';
import { Body } from '@/5_shared/ui/Body/Body';
import './globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="ru">
            <Body className={classNames(inter.className)}>
                <Header />
                {children}
                <Footer />
            </Body>
        </html>
    );
}
