import { ReactNode } from 'react';
import classNames from 'classnames';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '2_widgets/Header';
import { Footer } from '2_widgets/Footer';
import { Body } from '5_shared/ui/Body/Body';
import './globals.scss';
import StoreProvider from '../5_shared/state/StoreProvider';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface LayoutProps {
    children: ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
    return (
        <html lang="ru">
            <StoreProvider>
                <Body>
                    <Header />
                    {children}
                    <Footer />
                </Body>
            </StoreProvider>
        </html>
    );
}
